### ISSUE TITLE
Failed to load the max-tabs package

### ISSUE THREAD

**Issue by ssijak** [klorenz/atom-max-tabs#4]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.19
**System**: Mac OS X 10.11
**Thrown From**: [max-tabs](https://github.com/klorenz/atom-max-tabs) package, v0.3.1
### Stack Trace

Failed to load the max-tabs package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
  at __extends (/Users/ssijak/.atom/packages/max-tabs/lib/max-tabs-view.coffee:1:1)
  at /Users/ssijak/.atom/packages/max-tabs/lib/max-tabs-view.coffee:5:3
  at Object.<anonymous> (/Users/ssijak/.atom/packages/max-tabs/lib/max-tabs-view.coffee:52:5)
  at Object.<anonymous> (/Users/ssijak/.atom/packages/max-tabs/lib/max-tabs-view.coffee:1:1)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .coffee] (/opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.<anonymous> (/Users/ssijak/.atom/packages/max-tabs/lib/max-tabs.coffee:1:15)
  at Object.<anonymous> (/Users/ssijak/.atom/packages/max-tabs/lib/max-tabs.coffee:1:1)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .coffee] (/opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Package.module.exports.Package.requireMainModule (/opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/src/package.js:761:34)
  at /opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/src/package.js:192:28
  at Package.module.exports.Package.measure (/opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/src/package.js:169:15)
  at Package.module.exports.Package.load (/opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/src/package.js:183:12)
  at PackageManager.module.exports.PackageManager.loadPackage (/opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/src/package-manager.js:405:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/src/package-manager.js:485:30)
  at /opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:371:29
  at exit (/opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:60:16)
  at triggerExitCallback (/opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
  at /opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:220:18
  at Socket.<anonymous> (/opt/homebrew-cask/Caskroom/atom/1.0.19/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:98:18)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:169:7)
  at Pipe._onclose (net.js:467:12)

```
### Commands

```
     -0:30.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
angular-jonpapa-snippets, v0.6.0
angularjs, v0.3.3
atom-beautify, v0.28.14
atom-jade, v0.3.0
atom-python-debugger, v0.3.4
atom-ternjs, v0.8.2
autocomplete-paths, v1.0.2
autocomplete-python, v0.6.2
autocomplete-sass, v0.1.0
bottom-dock, v0.3.5
code-links, v0.3.11
color-picker, v2.0.13
css-color-underline, v1.0.1
css-snippets, v0.9.0
emmet, v2.3.13
gulp-manager, v0.2.10
language-SCSS, v0.4.0
language-diff, v0.3.1
linter, v1.8.1
linter-csslint, v1.1.0
max-tabs, v0.3.1
minimap, v4.13.4
pigments, v0.17.1

# Dev
No dev packages
```

**Comment by klorenz** [comment]
Hi Sasa,

I stopped developing this package in favour of 
https://atom.io/packages/tidy-tabs.  Please use that package.

Best regards, Kiwi

Am 15.10.2015 um 10:23 schrieb Saša Šijak:
